### PR TITLE
(Fix) title of dApp

### PR DESCRIPTION
**Pull request by vbaranov**
- Relates to #53
- links to sokol and core in two lines in README

### CODE REVIEW

**Comment by igorbarinov** [comment]
@vbaranov do we need the same PR for the `sokol` branch?

**Comment by vbaranov** [comment]
@igorbarinov Oh, I've already changed it for sokol here https://github.com/poanetwork/poa-dapps-keys-generation/commit/6be6b3ae73c74c0d0a88a47bcfaa0aba1b30bbec. I'll follow the same PR policy, as for core branch, in the future. By the way, there is no PR policy described in wiki for PoA Network Dapps yet.

**Comment by igorbarinov** [comment]
@vbaranov please use POA Network instead of PoA Network :-)
PoA is a consensus algorithm.

**Comment by vbaranov** [comment]
@igorbarinov I made an update to PR to fit title style with suggested here: https://github.com/poanetwork/poa-dapps-voting/pull/31/files/ab1761adf93cfd81c999fb66f1ec9a9ef8567e83#r158846016

**Review by rstormsf — APPROVED** [review]

**Pull request merged**
