### PR TITLE
(Feature) Automatically save all keys with its passwords

### PR DESCRIPTION
**Pull request by rstormsf**
(Problem): Many of our validators didn't save passwords during ceremony process.
(Solution): Save all keys with its passwords in 1 file

### CODE REVIEW

**Review by vbaranov — COMMENTED** [review]
@rstormsf everything is fine. Maybe, let's move zip file generation after success transaction response? Because zip file is downloaded immediately after clicking to button `generate keys`. Even in case if I reject the transaction.

**Comment by rstormsf** [comment]
@vbaranov good point, however I'd need to support `#just-generate-keys` URL as well.
Any suggestion?

**Comment by rstormsf** [comment]
@vbaranov fixed!

**Review by vbaranov — COMMENTED** [review]
Perfect

**Review by vbaranov — APPROVED** [review]

**Pull request merged**
